### ISSUE TITLE
Leg 2 No Minimap ( V)  No Route note (S)  and no custom toolbar selectable

### ISSUE THREAD

**Issue by RansFlyer** [marccreal/AndalusiaBushTrip#3]
What has happened ??

**Comment by marccreal** [comment]
This sounds like an issue I already encountered even with the built-in bush trips. So sadly it is quite probably a bug in the sim. It happens when you begin a new leg but then exit. The flight is saved but when you then use the "Continue" in the bush trip menu, the loading of the saved flight seems to not work correctly and these strange things happen. I will investigate further, but as a workaround, you could restart from one leg before and then use the developer menu to jump to the destination airport of this leg to trigger the next one.

**Comment by marccreal** [comment]
This specific bug turned out to be a configuration error in the my FLT file (my bad!). The bug is fixed with v0.2b. You probably have to restart the trip from the beginning, but you can then jump forward with the developer menu (see [readme](../blob/master/README.md)).
